version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: studywise_postgres
    restart: always
    environment:
      POSTGRES_DB: studywise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    image: php:8.1-apache-bullseye
    container_name: studywise_php
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    build:
      context: ./docker/php/
      dockerfile: Dockerfile


  pgadmin:
    image: dpage/pgadmin4
    container_name: studywise_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: